language: c
sudo: required
dist: trusty

os:
  - osx
  - linux

compiler:
  - gcc

env:
  matrix:
    - CFLAGS=-m64 LDFLAGS=-m64
    - CFLAGS=-m32 LDFLAGS=-m32

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gcc-multilib ;  fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CC=gcc-4.9 ; fi

script:
  - $CC -pthread example-pthreads.c

