#os: Visual Studio 2015

environment:
  matrix:
    - platform: Win32
      prefix_dir: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32
    - platform: x64
      prefix_dir: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64

before_build:
  - set PATH=%PATH:C:\Program Files (x86)\Git\usr\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=%prefix_dir%\bin;%PATH%
  - if [%PLATFORM%]==[x64]   set CFLAGS=-m64
  - if [%PLATFORM%]==[x64]   set LDFLAGS=-m64
  - if [%PLATFORM%]==[Win32] set CFLAGS=-m32
  - if [%PLATFORM%]==[Win32] set LDFLAGS=-m32

build_script:
  - gcc example-winapi-messageloop.c
  - gcc example-winapi.c

before_test:

test_script:
